movierecsite/main/routes.py
from flask import Blueprint, render_template, request

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def main_page():
    return render_template('home.html')

@main.route("/about")
def about_page():
    return render_template('about.html', title='About')

@main.route("/recent_movies")
def recent_movies_page():
    return render_template('recent_movies.html', title='Recent Movies')

@main.route("/genres")
def genres_page():
    return render_template('genres.html', title='Genres')

movierecsite/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from movierecsite import db, bcrypt
from movierecsite.users.forms import SignUpForm, SignInForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from movierecsite.models import User
from flask_login import login_user, current_user, logout_user, login_required
from movierecsite.users.utils import send_reset_email

users = Blueprint('users', __name__)

@users.route("/sign_in", methods=['GET', 'POST'])
def sign_in_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.main_page'))
    form = SignInForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next') #This is to simply redirect to a page that a user was trying to access before logging in.
            return redirect(next_page) if next_page else redirect(url_for('main.main_page')) #redirects to the next page if it exists. Otherwise, go to home page.
        else:
            flash('Login Failed. Please check email and paassword', 'danger')
    return render_template('sign_in.html', title='Sign In', form=form)

@users.route("/sign_up", methods=['GET', 'POST'])
def sign_up_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.main_page'))
    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') #hashing password. Using .decode('utf-8') to make it a string instead of binary.
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user) #add user to the database
        db.session.commit() #commit changes to database
        flash('Your account has been created!', 'sucess')
        return redirect(url_for('users.sign_in_page'))
    return render_template('sign_up.html', title='Sign Up', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.main_page'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been successfully updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.main_page'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.sign_in_page'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.main_page'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for(users.reset_request))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8') #hashing password. Using .decode('utf-8') to make it a string instead of binary.
        user.password = hashed_password
        db.session.commit() #commit changes to database
        flash('Your password has been updated!', 'sucess')
        return redirect(url_for('users.sign_in_page'))
    return render_template('reset_token.html', title='Reset Password', form=form)

movierecsite/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="../static/about.css">
    <div class="team-section">
        <h1>Meet developers!</h1>
        <span class="border"></span>
        <div class="ps">
            <a href="#p1"><img src="https://lh3.googleusercontent.com/2o-HIfxKpbf2h7aLONS7X9VOIuyR0ISkXADVPuZLF1R7ujdyaYjqtBGkiKMFCHw9XqmorvgDfihshC5iw4BvyvtJA7u3uvfkexaDz2mLi63proDo6fyhPLdRnPjnAxhHkZOmX_z2Ww=w2400?source=screenshot.guru"> <img src="https://lh3.googleusercontent.com/2o-HIfxKpbf2h7aLONS7X9VOIuyR0ISkXADVPuZLF1R7ujdyaYjqtBGkiKMFCHw9XqmorvgDfihshC5iw4BvyvtJA7u3uvfkexaDz2mLi63proDo6fyhPLdRnPjnAxhHkZOmX_z2Ww=w600-h315-p-k" alt="Hakyung Yun"></a>
            <a href="#p2"><img src="https://lh3.googleusercontent.com/qM5P8Qj4-yxkrKGGXwMUtjM6BbjV_KHivM6_e1PgqEOXBr2aKC0uPn7KC0zMy_3QjmuC33BaesUujqCeRhS8IanGVHlskzPc_-paJt3t9_9Gw4IhY5S6rM53hUs1VIl-hSzuChVeVQ=s299-p-k" alt="Earl chae"></a>
        </div>
    <!-- target="_blank" opens the linked page in a new tab or window. It is a useful feature, but there is a security risk that we should be aware of. -->
    <!-- The new tab gains limited access to the linking page via window.opener, which it can then use to alter the linking page's URL via window.opener.location -->
    <!-- This might be a problem if the external resource is not trustworthy; migt have been hacked, the domain has changed owners over the years etc. -->
    <!-- In order to prevent such risk, I am adding rel="noopener noreferrer" attribute to all of target="_blank" links -->
    <!-- Saw it from a instgram post -->
    <!-- excerpted from https://codepen.io/SeedThemes/pen/kkQaNE and modified github icon hover effect.-->
    <div class="section" id="p1">
        <span class="name">Hakyung Yun</span>
        <span class="border"></span>
        <p>Hakyung, who also goes by Peter, is a sophomore undergraduate student at the University of Illinois at Urbana-Champaign, studying Computer Engineering. He spent most of his life in Korea but has gone to school in America since 2017. His top interests are software engineering, web development, and data analytics.</p>
        <br>
        <div class="icons-align">
        <a class="fa fa-github hover-fx" style="font-size:40px" href="https://github.com/hakyung4" target="_blank" rel="noopener noreferrer"></a>
        <!-- Horizontal space between icons -->
        <span style="display:inline-block; width: 0px;"></span>
        <a class="fa fa-linkedin-square hover-fx" style="font-size: 40px" href="https://www.linkedin.com/in/hakyung-peter-yun-3204061b8/" target="_blank" rel="noopener noreferrer"></a>
        <span style="display:inline-block; width: 0px;"></span>
        <a class="fa fa-envelope hover-fx" style="font-size: 40px" href="mailto: hamiram9@gmail.com"></a>
        </div>
    </div>
    
    <div class="section" id="p2">
        <span class="name">Earl Chae</span>
        <span class="border"></span>
        <p>Hyobjeong Chae, who also goes by Earl, is a senior undergraduate student at the University of Illinois at Urbana-Champaign, studying Statistics and Industrial Engineering. His eagerness and passion for learning led his educational journey to America. His top interests are data analytics and IT consulting.</p>
        <br>
        <div class="icons-align">
        <a class="fa fa-github hover-fx" style="font-size:40px" href="https://github.com/HYOB99" target="_blank" rel="noopener noreferrer"></a>
        <span style="display:inline-block; width: 0px;"></span>
        <a class="fa fa-linkedin-square hover-fx" style="font-size:40px" href="https://www.linkedin.com/in/earlchae/" target="_blank" rel="noopener noreferrer"></a>
        <span style="display:inline-block; width: 0px;"></span>
        <a class="fa fa-envelope hover-fx" style="font-size: 40px" href="mailto: darktempler120@gmail.com"></a>
        </div>
    </div>
    <br><br><br>
    <p>The source code for this project can be found <a class="text-color" href="https://github.com/HYOB99/MovieRecSite" target="_blank" rel="noopener noreferrer"><u>here</u></a>.</p>
    <br>
{% endblock content %}

movierecsite/templates/account.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="../static/forms.css">
<div class="content-section bigger-text">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
            <h1>Account Info</h1>
            <br>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span><br>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span><br>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        <br><br><br>
            <div class="button-center">
            <button class="btn btn-primary center" type="submit">Update</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

movierecsite/templates/genres.html
{% extends "layout.html" %}
{% block content %}
    <h1>Genres</h1><br>
<div class="genres-text">
    <p>Action</p>
</div>
<div class="genres-text">
    <p>Animation</p>
</div>
<div class="genres-text">
    <p>Comedy</p>
</div>
<div class="genres-text">
    <p>Drama</p>
</div>
<div class="genres-text">
    <p>Fantasy</p>
</div>
<div class="genres-text">
    <p>Horror</p>
</div>
{% endblock content %}

movierecsite/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>Movie Recommendation For You</h1>
{% endblock content %}

movierecsite/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel="stylesheet" href="../static/main.css">
    {% if title %}
        <title>{{title}}</title>
    {% else %}
        <title>Home Page</title>
    {% endif %}
</head>
<body>
<header>
    <!-- Getting ride of GET/favicon.ico http/1.1 404 not found error. -->
    <link rel="shortcut icon" href="">
    <img src="https://api.freelogodesign.org/files/b09c45b71eb54116b4ecba31cad6cf86/thumb/logo_200x200.png?v=0" alt="Logo Pictures" width="125px" height="125px">
    <!--Decided to name this site "Movie Picker" 
    Imported the logo from https://editor.freelogodesign.org/?category=15&companyName=Movie%20Picker.
    Free to create and download. No copyright issues. -->
    <nav>
        <ul class="nav_links">
            <li><a href="{{ url_for('main.main_page') }}">Home</a></li>
            <li><a href="{{ url_for('main.about_page') }}">About</a></li>
            <li><a href="{{ url_for('main.genres_page') }}">Genres</a></li>
            <li><a href="{{ url_for('main.recent_movies_page') }}">Recent movies</a></li>
        </ul>
    </nav>
        {% if current_user.is_authenticated %}
            <a class="cta" href="{{ url_for('users.account') }}"><button>Account</button></a>
            <a class="cta" href="{{ url_for('users.logout') }}"><button>Sign Out</button></a>
        {% else %}
            <a class="cta" href="{{ url_for('users.sign_in_page') }}"><button>Sign in</button></a>
            <a class="cta" href="{{ url_for('users.sign_up_page') }}"><button>Sign up</button></a>
        {% endif %}
</header>
        <div class="message-box">
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- with_categories=true gets sucess messages; bootstrap class -->
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        </div>
        {% block content %}{% endblock %}
</html>

movierecsite/templates/recent_movies.html
{% extends "layout.html" %}
{% block content %}
    <h1>Recent Movies</h1>
{% endblock content %}

movierecsite/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="../static/forms.css">
<div class="content-section bigger-text">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <h1>Reset Password</h1>
            <br>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
        </fieldset>
        <br>
        <div class="form-group center">
            <button class="btn btn-primary" type="submit">Request Reset Password</button>
        </div>
        <br>
    </form>
</div>
{% endblock content %}

movierecsite/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="../static/forms.css">
<div class="content-section bigger-text">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <h1>Reset Password</h1>
            <br>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <br>
        <div class="form-group center">
            <button class="btn btn-primary" type="submit">Reset Password</button>
        </div>
        <br>
    </form>
</div>
{% endblock content %}

movierecsite/templates/sign_in.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="../static/forms.css">
<div class="content-section bigger-text">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <h1>Sign In</h1>
            <br>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <!-- remember me? -->
            <div class="form-check"> 
                {{ form.remember(class="form-check-input") }}
                {{ form.remember.label(class="form-check-label") }}
            </div>

        </fieldset>
        <br>
        <div class="form-group center">
            <button class="btn btn-primary" type="submit">Sign In</button>
        </div>
        <br>
        <small class="text-muted ml-2">
            <a class="forgot-pw" href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
        </small>
    </form>
</div>
<div class="bigger-text">
    <small class="text-muted">
        Don't Have An Account? 
        <br><br>
        <a class="center" href="{{ url_for('users.sign_up_page') }}"><button>Sign Up</button></a>
    </small>
    <br>
</div>
{% endblock content %}

movierecsite/templates/sign_up.html
{% extends "layout.html" %}
{% block content %}
<link rel="stylesheet" href="../static/forms.css">
<div class="content-section bigger-text">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <h1>Sign up</h1>
            <br>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                <!-- check for validation errors -->
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <br>
        </fieldset>
        <br>
        <div class="form-group center">
            <button class="btn btn-primary" type="submit">Sign Up</button>
        </div>
    </form>
</div>

<div class="bigger-text">
    <small class="text-muted">
        Already Have An Account? 
        <br><br>
        <a class="center" href="{{ url_for('users.sign_in_page') }}"><button>Sign In</button></a><br>
    </small>
</div>
{% endblock content %}